### ISSUE TITLE
How to use？

### ISSUE THREAD

**Issue by w657395940** [wanyaworld/ZonFS#1]
Hi，could you kindly give me a specification to show the main setup steps? 
The kernel prompts that slub is unable to allocate memory from node 1 when booting.

**Comment by wanyaworld** [comment]
Hello.
In our implementation, some memory address is hard-coded.
And we slightly modified some code from sl*b allocators.
We tested in two x86 machine which are NUMA and UMA, and it worked.
Can u let me know about your hardware detail?

**Comment by w657395940** [comment]
Thank you for your reply.
Our platform is a two-node NUMA server with 256GB DRAM.

wt@wt:~$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                40
On-line CPU(s) list:   0-39
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Stepping:              1
CPU MHz:               3248.343
BogoMIPS:              4791.75
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-9,20-29
NUMA node1 CPU(s):     10-19,30-39

wt@wt:~$ free -g
             total       used       free     shared    buffers     cached
Mem:           251          1        250          0          0          0

**Comment by wanyaworld** [comment]
Okay.
Can you also show the result of 
“numactl --hardware” ?
It may require you to install a package.

**Comment by w657395940** [comment]
The kernel-make is passed. 
However, it is failed at the booting stage.
The log prompts that:
  [00000.1] Slub: unable to allocate memory for node 1
  [00000.1] Slub: allocating a useless per node structure in order to be continue

**Comment by w657395940** [comment]
wt@wt:~$ numactl --hardware
available: 2 nodes (0-1)
node 0 cpus: 0 1 2 3 4 5 6 7 8 9 20 21 22 23 24 25 26 27 28 29
node 0 size: 128847 MB
node 0 free: 128351 MB
node 1 cpus: 10 11 12 13 14 15 16 17 18 19 30 31 32 33 34 35 36 37 38 39
node 1 size: 129010 MB
node 1 free: 128469 MB
node distances:
node   0   1 
  0:  10  21 
  1:  21  10

**Comment by wanyaworld** [comment]
After searching the error message, i could  find that early_kmem_cache_node_alloc() in mm/slub.c is generating the message.
I think it is NUMA related issue.
Maybe it is possible that i didn’t test on NUMA machine.
Will test this issue in NUMA environments.

**Comment by w657395940** [comment]
We also test it on a UMA server and encounter the same error.
Thank you very much for your assistance and look forward to fixing it.

**Comment by wanyaworld** [comment]
This was due to two problems.

1) The address and size of STORAGE_ZONE might have been improper for machines with few memory.
This was applied to commit a9cee9905afbccec93a07c651de6348efed66dec, though it is possible that it won't work for machines with memory less than 16GB.

2) In Linux kerlen 4.7.4, on which the ZonFS is built, the maximum number of memory zones was 4.
The user needs to restrain the number of zones to 3, thus saving one zone for ZONE_STORAGE.

Will close the issue.

**Comment by w657395940** [comment]
Thank you very much ！
It works after restraining the number of zones.
